name: greycode
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-5.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^3.3.13
  google_sign_in: ^5.2.4
  firebase_core: ^1.14.0
  shared_preferences: ^2.0.13
  cloud_firestore: ^3.1.11
  stream_chat_flutter: ^3.5.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  # flutter_lints: ^2.0.0


dependency_overrides:
  video_compress:
      git:
        url: https://github.com/jonataslaw/VideoCompress.git
        ref: master


flutter:

  uses-material-design: true
  assets:
    - assets/Images/
  
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/Fonts/GoogleSans-Regular.ttf
        - asset: assets/Fonts/GoogleSans-Bold.ttf


